# Generated by Django 4.0.5 on 2022-06-26 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название альбома')),
                ('artist', models.CharField(max_length=100, verbose_name='Артист')),
                ('poster', models.ImageField(upload_to='', verbose_name='Обложка альбома')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'db_table': 'album',
                'unique_together': {('name', 'artist', 'poster')},
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order', models.IntegerField(verbose_name='Номер композиции')),
                ('title', models.CharField(max_length=100, verbose_name='Название композиции')),
                ('duration', models.IntegerField(verbose_name='Длительность')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='someapp.album')),
            ],
            options={
                'verbose_name': 'Композиция',
                'verbose_name_plural': 'Композиции',
                'db_table': 'Track',
                'unique_together': {('album', 'order')},
            },
        ),
    ]
