# Generated by Django 4.0.5 on 2022-06-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someapp', '0002_alter_track_duration_alter_track_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
