# Generated by Django 4.0.5 on 2022-06-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someapp', '0003_alter_album_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.PositiveSmallIntegerField(verbose_name='Длительность в секундах'),
        ),
    ]
