# Generated by Django 4.0.5 on 2022-06-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('someapp', '0005_alter_track_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='track',
            table='track',
        ),
    ]
